
baseURL = 'https://aidenvaines-cgi.github.io/voice-of-engineering-blog-aggregator/'
title = 'Voice of Engineering Blog Aggregator'
theme = 'cgi-theme'
defaultContentLanguage = 'en'

[languages]
  [languages.en]
    languageCode = 'en-GB'
    languageName = 'English'
    weight = 1
    [languages.en.params]
      description = 'CGI Engineering blog aggregator showcasing thought leadership from our experts'

  [languages.fr]
    languageCode = 'fr-FR'
    languageName = 'Français'
    weight = 2
    title = 'Agrégateur de blogs Voice of Engineering'
    [languages.fr.params]
      description = "Agrégateur de blogs d'ingénierie CGI présentant le leadership éclairé de nos experts"

[params]
  heroImage = 'hero.png'
  defaultPostImage = 'defaultPost.jpg'

[taxonomies]
  tag = 'tags'
  author = 'authors'
